[workspace]
resolver = "2"
members = [
    "examples/term3d",
    "examples/alpha",
    "examples/animation",
    "examples/dot",
    "examples/minimal",
    "examples/snake",
    "examples/water",
    "term2d",
]
